//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab4_CRUD_hw.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public decimal dId { get; set; }
        public string dname { get; set; }
    }
}
